### ISSUE TITLE
Zero shot protocol

### ISSUE THREAD

**Issue by chanhoeom** [valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition#1]
Hi~
Thanks for the awesome baseline code! :)

I want my model train on the zero-shot setting you proposed in the paper in arXiv
(Rethinking of Pedestrian Attribute Recognition- Realistic Datasets and A Strong Baseline)

Can you share the new protocol you proposed?

Thanks in advance

**Comment by valencebond** [comment]
hi @chanhoeom , i will release the zero-shot protocal in this week,  please stay tuned

**Comment by valencebond** [comment]
hi @chanhoeom , we now provide the new protocol.  You can try it.
