### ISSUE TITLE
PETA.mat缺失

### ISSUE THREAD

**Issue by lergliu** [valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition#19]
PETA.mat数据是哪来的呢？下载的数据集里没有啊

**Comment by Pyten** [comment]
同问，连接里的PETA的标注是txt文件，MAT从那里获取呢？

**Comment by valencebond** [comment]
please find the peta.mat file at https://drive.google.com/file/d/1Wmqqw-VkA5AjD459VIy7DzNk7CFq-ZtL/view?usp=sharing

> 同问，连接里的PETA的标注是txt文件，MAT从那里获取呢？
