### ISSUE TITLE
互斥属性如何保证结果互斥

### ISSUE THREAD

**Issue by lergliu** [valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition#20]
您好，
看了您的代码。我想问一下，这种多标签任务，一般操作都是把age作为一个属性，[young,teenager,adult,old]是这个属性的四个选项，用softmax判断。 我看代码中是对4个属性设置了4个分类器， 如何保证不会出现[1,1,0,0]既是young又是teenager的情况？

**Comment by northeastsquare** [comment]
可以4选一，概率最大的

**Comment by zhangjingling** [comment]
> 您好，
> 看了您的代码。我想问一下，这种多标签任务，一般操作都是把age作为一个属性，[young,teenager,adult,old]是这个属性的四个选项，用softmax判断。 我看代码中是对4个属性设置了4个分类器， 如何保证不会出现[1,1,0,0]既是young又是teenager的情况？


你好，请问infer.py文件我运行时出现错误，github上有人问过的。能否把你的infer.py文件发我看看。此外，我想知道如何出现测试结果图片？   13137730606@163.com
