### ISSUE TITLE
What is the password of the data set RAP V1 compressed file？

### ISSUE THREAD

**Issue by ShawKai666** [valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition#29]

**Comment by valencebond** [comment]
you can get it from the [website](http://www.rapdataset.com/)

**Comment by ShawKai666** [comment]
> you can get it from the [website](http://www.rapdataset.com/)

![image](https://user-images.githubusercontent.com/35207527/104285262-4fa38c00-54ee-11eb-9725-2af51f3a4b9f.png)

I have submitted the form, but did not receive the feedback email。

**Comment by valencebond** [comment]
hi @ShawKai666 , can you give me an email address? I will send the password to you.

**Comment by ShawKai666** [comment]
> hi @ShawKai666 , can you give me an email address? I will send the password to you.

hi @valencebond ，my email address is   shockailee@gmail.com

**Comment by ShawKai666** [comment]
> hi @ShawKai666 , can you give me an email address? I will send the password to you.

hi @valencebond ,my email address is 358922150@qq.com,thanks!
