### ISSUE TITLE
How to load your pretrained weights for inference?

### ISSUE THREAD

**Issue by sayanmutd** [valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition#3]
How can we load the pretrained weights for inference? Can we provide the sample code for inference?

**Comment by huytran97** [comment]
You can try this code to change your state_dicts key and load pretrained weights: 

backbone = resnet50()
classifier = BaseClassifier(nattr=26)
model = FeatClassifier(backbone, classifier)

checkpoint = torch.load('/home/user/Downloads/pa100k_ckpt_max.pth', map_location='cpu')

state_dict = checkpoint['state_dicts']
new_state_dict = OrderedDict()
for k, v in state_dict.items():
    name = k[7:]
    new_state_dict[name] = v
# load params
model.load_state_dict(new_state_dict)
model.eval()

**Comment by tianhaoyue** [comment]
> 您可以尝试以下代码来更改state_dicts键并加载预训练的权重：
> 
> 主干= resnet50（）
> 分类器= BaseClassifier（nattr = 26）
> 模型= FeatClassifier（骨干，分类器）
> 
> 检查点= torch.load（'/ home / user / Downloads / pa100k_ckpt_max.pth'，map_location ='cpu'）
> 
> state_dict =检查点['state_dicts']
> new_state_dict = state_dict.items （）
> 中k，v的OrderedDict（）：
> 名称= k [7：]
> new_state_dict [name] = v
> 
> # 加载参数
> model.load_state_dict（new_state_dict）
> model.eval（）

Can you provide the complete reasoning code for reference, you can send it to my mailbox:376656153@qq.com

**Comment by tianhaoyue** [comment]
> You can try this code to change your state_dicts key and load pretrained weights:
> 
> backbone = resnet50()
> classifier = BaseClassifier(nattr=26)
> model = FeatClassifier(backbone, classifier)
> 
> checkpoint = torch.load('/home/user/Downloads/pa100k_ckpt_max.pth', map_location='cpu')
> 
> state_dict = checkpoint['state_dicts']
> new_state_dict = OrderedDict()
> for k, v in state_dict.items():
> name = k[7:]
> new_state_dict[name] = v
> 
> # load params
> model.load_state_dict(new_state_dict)
> model.eval()

Can you provide the complete reasoning code for reference, you can send it to my mailbox376656153@qq.com

**Comment by vakkov** [comment]
one-liner:

model.load_state_dict({k.replace('module.', ''): v for k, v in pretrained_dict['state_dicts'].items()})
