### ISSUE TITLE
decompression password

### ISSUE THREAD

**Issue by hsl8856** [valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition#4]
What is the decompression password after downloading the RAP data set

**Comment by valencebond** [comment]
hi @hsl8856  please visit [RAP website]( http://www.rapdataset.com/) and fill the agreement.

**Comment by hsl8856** [comment]
thank you




| |
洪石林
|
|
邮箱：18855583063@163.com
|

签名由 网易邮箱大师 定制

On 06/29/2020 08:41, Jian wrote:

hi @hsl8856 please visit RAP website and fill the agreement.
