### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by vtimofeev01** [valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition#6]
Please tell how to convert an multilabel CSV dataset in mat file
Thank U

**Comment by valencebond** [comment]
you dont have to.  You can just change [lines of code](https://github.com/valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition/blob/97e33338432d277596dcb1958292b070facfd6ff/dataset/AttrDataset.py#L19-L24) to reload your images and labels.

**Comment by vtimofeev01** [comment]
What the format / how to prepare a pkl-file / how to prepare right

        img_id = dataset_info.image_name              <- list of files
        attr_label = dataset_info.label                      <- ?? 
        self.attr_id = dataset_info.attr_name            <- list - name of attributes (columns) 
        self.img_idx = dataset_info.partition[split]   < ndarray  len_of_dataset x num_of_attributes dtype=int

**Comment by vtimofeev01** [comment]
Something like this?

        data_path = args.dataset
        self.root_path = data_path
        v = {'trainval': 'train_n.csv',
             'test': 'test_n.csv'}
        fname = os.path.join(data_path, v[split])
        df = pd.read_csv(fname)
        attrs = df.columns
        self.img_id = df['image']
        self.label = df[attrs[1:]].to_numpy()
        self.attr_num = attrs.shape[0] - 1
        self.img_idx = np.array(list(range(self.label.shape[0])))
        self.transform = transform
        self.target_transform = target_transform

**Comment by valencebond** [comment]
hi @vtimofeev01 , yes, you just need to replace self.img_idx and self.label with your own images and groundtruth labels
