### ISSUE TITLE
Strong Baseline trained in proposed dataset?

### ISSUE THREAD

**Issue by zhaiyutong** [valencebond/Strong_Baseline_of_Pedestrian_Attribute_Recognition#7]
Hello, thank you for your paper and your code!
I have read your paper and code, but there is one thing I couldn't understand well.
How did you get your strong baseline model?  Is it trained in your two proposed dataset separately or jointly?  

作者你好，非常感谢你提供的论文和代码！
在阅读你论文和复现你代码的过程中，我不太明白你的strong baseline是怎么训出来的？因为基于你论文中的描述，你只是在resnet的基础上修改了损失函数。你是在你提出的两个数据集上分别还是联合在一起训练的？如果没有理解错的话，你的strong baseline之所以可以在别的数据集上比别的算法表现的好，只是因为它在一个更好的数据集上训练了？
非常感谢你的回复，如果有理解不对的地方，希望指出，谢谢！

**Comment by valencebond** [comment]
hi @zhaiyutong , wo do not pre-train the model on our proposed datasets. For example, model for RAP datasets is just trained on RAP dataset without any other datasets. We have provided detailed code and training procedure, you can just try.
